name: docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: ${{ runner.os }}-stack-

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true

    - name: Build dependencies
      run: stack build --only-dependencies

    - name: Run Haddock
      run: stack haddock --haddock-arguments --odir=public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
