name: test

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Haskell
      uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true

    - name: Build dependencies
      run: stack build --test --only-dependencies

    - name: Build
      run: stack build

    - name: Run tests
      run: stack test
