name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}

    - name: Build dependencies
      run: stack --system-ghc build --test --only-dependencies

    - name: Build
      run: stack --system-ghc build

    - name: Run unit tests
      run: stack --system-ghc test

    - name: Run integrated tests
      run: bash examples/test.sh
