name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - name: Build dependencies
      run: stack build --test --only-dependencies

    - name: Build
      run: stack build

    - name: Run unit tests
      run: stack test

    - name: Run integrated tests
      run: bash examples/test.sh
